name: Build & Push container

on:
  workflow_call:
    inputs:
      target:
        type: string
        default: production
        description: The build target as specified in the Dockerfile
      tags:
        type: string
        required: true
        description: Tags to used for the image
      composer-install-args:
        type: string
        default: --no-interaction --optimize-autoloader
        description: Composer install args

jobs:
  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: colpal/actions-clean@v1
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        id: build
        uses: docker/build-push-action@v5
        with:
          target: ${{ inputs.target }}
          secrets: |
            COMPOSER_AUTH=${{ vars.COMPOSER_AUTH_JSON_BASE64 }}
          build-args: |
            COMPOSER_INSTALL_ARGS="${{ inputs.composer-install-args }}"
          push: true
          no-cache: true
          tags: ${{ inputs.tags }}
