on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

name: Container build to Quay.io

jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Prepare image version and tags
          id: prepare-version-tags
          run: |
            DOCKER_IMAGE=quay.io/superbrave/blueclinic

            # Determine version.
            VERSION=noop
            if [[ $GITHUB_REF == refs/pull/* ]]; then
              VERSION=${{ github.event.pull_request.head.ref }}
            elif [[ $GITHUB_REF == refs/tags/* ]]; then
              VERSION=${GITHUB_REF#refs/tags/}
            elif [[ $GITHUB_REF == refs/heads/* ]]; then
              VERSION=edge
            fi
            # Replace characters with a dash (-) that are invalid in a Docker image tag.
            VERSION=${VERSION//\//-}

            # Determine image tags
            TAGS="${DOCKER_IMAGE}:${VERSION}"
            if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
              MINOR=${VERSION%.*}
              MAJOR=${MINOR%.*}
              TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
            fi

            echo ::set-output name=version::${VERSION}
            echo ::set-output name=tags::${TAGS}
            echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      -   name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

      -   name: Cache Docker layers
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-

      -   name: Login to Quay.io
          uses: docker/login-action@v1
          with:
            registry: quay.io
            username: ${{ secrets.QUAY_USERNAME }}
            password: ${{ secrets.QUAY_ACCESS_TOKEN }}

      -   name: Build and push images
          id: build
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./.docker/php-fpm/production/Dockerfile
            push: ${{ github.event_name != 'pull_request' || !contains(github.event.pull_request.head.ref, 'dependabot/') }}
            tags: ${{ steps.prepare-version-tags.outputs.tags }}
            labels: |
              org.opencontainers.image.title=${{ github.event.repository.name }}
              org.opencontainers.image.description=${{ github.event.repository.description }}
              org.opencontainers.image.url=${{ github.event.repository.html_url }}
              org.opencontainers.image.source=${{ github.event.repository.clone_url }}
              org.opencontainers.image.version=${{ steps.prepare-version-tags.outputs.version }}
              org.opencontainers.image.created=${{ steps.prepare-version-tags.outputs.created }}
              org.opencontainers.image.revision=${{ github.sha }}
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
